apiVersion: v1
kind: Service
metadata:
  namespace: web1
  labels:
    app: web1
  name: web1-service
spec:
  selector:
    app: web1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer